version: '3'

services:
  wsgi-server:
    build:
      context: .
      target: wsgi-server
    environment:
      APP_DOMAIN: localhost:9000
      WORKER_TIMEOUT: 180
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: password
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      ACCOUNT_EMAIL_VERIFICATION: ${ACCOUNT_EMAIL_VERIFICATION:-none}
      DB_URL: ${DB_URL:-sqlite:///db.sqlite3}
    ports:
      - '8000:8000'
    networks:
        - chatgpt-ui_network

  web-server:
    build:
      context: .
    environment:
      - BACKEND_URL=http://wsgi-server:8000
    ports:
      - '9000:80'
    depends_on:
      - wsgi-server
    networks:
      - chatgpt-ui_network

networks:
  chatgpt-ui_network:
    external: true
